---
title: "Replication"
author: "Christopher"
date: "2026-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data}
# Data from Conde et al:
df_fam <- read_xlsx("Conde_data/Conde_fam.xlsx")
df_other <- read_xlsx("Conde_data/Conde_other.xlsx")

# Data generated by me:
df_gen <- read_csv("gen.csv")
df_fa <- read_csv("fam_gen.csv")

# New frequency, suprisal and entorpy values:
df_combi <- read_csv("combi.csv")
```



```{r , echo=FALSE}

weighted_sum = GPT_FAM
word = Word
word_no_punct = Word

df_fa <- df_fa %>% rename(Word = word)
df_fa <- df_fa %>% rename(GPT_FAM = weighted_sum)
df_fam <- df_fam %>% rename(Word = word_no_punct)

df_fam <- df_fam %>% select(Word, GPT_FAM)
df_fa <- df_fa %>% select(Word, GPT_FAM)

## This creates one dataset containing the raitngs generated by Conde and myself:
df_fami <- rbind(df_fam, df_fa)

df_other <- df_other %>% select(Word, GPT_concr, GPT_val, GPT_arou, GPT_AoA_ft)
df_gen <- df_gen %>% rename("GPT_arou" = "arousal")
df_gen <- df_gen %>% rename("GPT_val" = "valence")
df_gen <- df_gen %>% rename("GPT_concr" = "concreteness")
df_gen <- df_gen %>% rename("GPT_AoA_ft" = "aoa")

df_others <- rbind(df_other, df_gen)






df_fami <- df_fami %>% group_by(Word) %>% summarise(GPT_FAM = mean(GPT_FAM, na.rm = TRUE))






df_correlation <- df_combi %>% left_join(df_fam, by = c("word_no_punct" = "Word"))
df_correlation <- df_correlation %>% left_join(df_fa, by = c("word" = "Word")


sum(is.na(df_correlation$GPT_FAM))
```



```{r}
df_combi_2 <- df_combi %>% left_join(df_fami, by = c("word_no_punct" = "Word")) ## Problem because more rows now!
df_combi_3 <- df_combi_2 %>% left_join(df_others, by = c("word_no_punct" = "Word"))

df_corr <- df_combi_3 %>% select(c(surprisal_2_words_context, entropy_2_words_context, frequency, zipf_frequency, GPT_FAM, GPT_concr, GPT_val, GPT_AoA_ft))

df_corr$surprisal_2_words_context <- as.numeric(df_corr$surprisal_2_words_context)
df_corr$entropy_2_words_context <- as.numeric(df_corr$entropy_2_words_context)
df_corr$frequency <- as.numeric(df_corr$frequency)
df_corr$zipf_frequency <- as.numeric(df_corr$zipf_frequency)
df_corr$GPT_FAM <- as.numeric(df_corr$GPT_FAM)
df_corr$GPT_concr <- as.numeric(df_corr$GPT_concr)
df_corr$GPT_val<- as.numeric(df_corr$GPT_val)
df_corr$GPT_arou<- as.numeric(df_corr$GPT_arou)
df_corr$GPT_AoA_ft<- as.numeric(df_corr$GPT_AoA_ft)

corr_pearson  <- cor(df_corr, use = "pairwise.complete.obs", method = "pearson")
corr_spearman <- cor(df_corr, use = "pairwise.complete.obs", method = "spearman")

# Combine matrices:
# upper triangle = Pearson, lower triangle = Spearman
corr_mixed <- corr_pearson
corr_mixed[lower.tri(corr_mixed)] <- corr_spearman[lower.tri(corr_spearman)]
corr_mixed <- round(corr_mixed, 2)



```


```{r}

ggcorrplot(
  corr_mixed,
  lab = TRUE,
  method = "square",
  type = "full",
  colors = c("white", "lightblue", "darkblue")
)+
  ggtitle("Correlations (Upper = Pearson, Lower = Spearman)") +
  theme(
    plot.title = element_text(size = 13, hjust = 0.5)
  ) +
  theme_bw()

```




