---
title: "Preprocessing_One"
author: "Christopher"
date: "2026-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
## This loads the required packages:
library(tidyverse)
library(here)
library(patchwork)
library(writexl)
library(ggcorrplot)


## This loads the required datasets.

### Ratings generated by Conde:
load(here::here("data/df_clean_all_subjects_09_24.RData"))
```




```{r pressure, echo=FALSE}
df_a <- df_clean %>% mutate(word_single = recode(word_single,
      "legend-ren" = "legendären",
      "Vig-a" = "Vigía",
      "zun-chst" = "zunächst",
      "ºbergeben" = "übergeben",
      "unver-ffentlichte" = "unveröffentlichte",
      "St-ºcke" = "Stücke",
      "bef-nden" = "befänden",
      "Bl-tter" = "Blätter",
      "Buchr-ºcken" = "Buchrücken",
      "Entw-ºrfe" = "Entwürfe",
      "gro-üen" = "großen",
      "ber-ºhmte" = "berühmte",
      "N-chte" = "Nächte",
      "schlie-ülich" = "schließlich",
      "gro-ü" = "groß",
      "au-üen" = "außen",
      "zur-ºckkehrt" = "zurückkehrt",
      "k-ºmmerte" = "kümmerte",
      "regelm-üig" = "regelmäßig",
      "ºber" = "über",
      "Gespr-che" = "Gespräche",
      "d-ºrfte" = "dürfte",
      "w-ºssten" = "wüssten",
      "w-ren" = "wären",
      "w-hrend" = "während",
      "j-ºngere" = "jüngere",
      "G-ste" = "Gäste",
      "z-hlte" = "zählte",
      "f-ºr" = "für",
      "Eigenbr-tler" = "Eigenbrötler",
      "pers-nlichen" = "persönlichen",
      "f-ºhlte" = "fühlte",
      "sp-ttischer" = "spöttischer",
      "R-ºhrend" = "Rührend",
      "versch-ºchtert" = "verschüchtert",
      "m-glicherweise" = "möglicherweise",
      "gr-üten" = "größten",
      "lie-ü" = "ließ",
      "v-llig" = "völlig",
      "ºberzeugen" = "überzeugen",
      "Tags-ºber" = "Tagsüber",
      "sp-ter" = "später",
      "sa-ü" = "saß",
      "Urlaubsbrosch-ºre" = "Urlaubsbroschüre",
      "Cham-leon" = "Chamäleon",
      "K-rpergr-üe" = "Körpergröße",
      "wei-ü" = "weiß",
      "Cham-leons" = "Chamäleons",
      "m-glich" = "möglich",
      "Ñste" = "Äste",
      "Gl-ºck" = "Glück",
      "Zerst-rung" = "Zerstörung",
      "gef-hrdet" = "gefährdet",
      "Cham-leon-Arten" = "Chamäleon-Arten",
      "gro-üe" = "große",
      "k-nnen" = "können",
      "hei-üt" = "heißt",
      "lie-üen" = "ließen",
      "Holl-nder" = "Holländer",
      "holl-ndischen" = "holländischen",
      "K-ºste" = "Küste",
      "H-user" = "Häuser",
      "W-lder" = "Wälder",
      "V-gel" = "Vögel",
      "nat-ºrlichen" = "natürlichen",
      "Ungl-ºck" = "Unglück",
      "F-ºr" = "Für",
      "vollst-ndig" = "vollständig",
      "gesch-digt" = "geschädigt",
      "verlie-üen" = "verließen",
      "Bev-lkerung" = "Bevölkerung",
      "Br-ºcken" = "Brücken",
      "Stra-üen" = "Straßen",
      "H-ndler" = "Händler",
      "l-sst" = "lässt",
      "spektakul-ren" = "spektakulären",
      "weltber-ºhmt" = "weltberühmt",
      "sch-nsten" = "schönsten",
      "W-ºste" = "Wüste",
      "Nabat-er" = "Nabatäer",
      "m-chtig" = "mächtig",
      "W-ºstenvolk" = "Wüstenvolk",
      "R-mer" = "Römer",
      "Weihrauchstra-üe" = "Weihrauchstraße",
      "H-hlen" = "Höhlen",
      "R-umen" = "Räumen",
      "au-üer" = "außer",
      "G-tter" = "Götter",
      "h-tten" = "hätten",
      "unm-glichen" = "unmöglichen",
      "Regenf-lle" = "Regenfälle",
      "Bew-sserungssystem" = "Bewässerungssystem",
      "úberall" = "überall",
      "Nabat-ern" = "Nabatäern",
      "str-mt" = "strömt",
      "M-uler" = "Mäuler",
      "Gew-ssern" = "Gewässern",
      "Oberfl-che" = "Oberfläche",
      "Sp-ter" = "Später",
      "rgerlich" = "ärgerlich",
      "L-ndern" = "Ländern",
      "pl-tzlichen" = "plötzlichen",
      "R-tsel" = "Rätsel",
      "pl-tzlich" = "plötzlich",
      "erw-rmte" = "erwärmte",
      "ungew-hnlich" = "ungewöhnlich",
      "Gl-ºcksfall" = "Glücksfall",
      "L-nge" = "Länge",
      "gr-üte" = "größte",
      "r-chte" = "rächte",
      "Mini-Cham-leons" = "Mini-Chamäleons",
      "bef-ºrchten" = "befürchten",
      "Gr-üe" = "Größe",
      "ºbertroffen" = "übertroffen",
      "k-nnte" = "könnte",
      "Gro-ü-Angkor" = "Groß-Angkor",
      "St-dte" = "Städte",
      "au-üerdem" = "außerdem",
      "Bew-sserungssystems" = "Bewässerungssystems",
      "Fl-ºssen" = "Flüssen",
      "Kan-len" = "Kanälen",
      "Ñckern" = "Äckern",
      "H-usern" = "Häusern",
      "Fl-che" = "Fläche",
      "Bew-sserungsnetz" = "Bewässerungsnetz",
      "st-rken" = "stärken",
      "Fl-chen" = "Flächen",
      "k-ºnstlichen" = "künstlichen",
      "Fl-ºsse" = "Flüsse",
      "Kan-le" = "Kanäle",
      "Waldfl-chen" = "Waldflächen",
      "f-ºhrte" = "führte",
      "Deichbr-ºchen" = "Deichbrüchen",
      "verr-t" = "verrät",
      "endg-ºltig" = "endgültig",
      "f-ºnf" = "fünf",
      "zweij-hrige" = "zweijährige",
      "M-dchen" = "Mädchen",
      "pfl-ºcken" = "pflücken",
      "M-ºhlteichs" = "Mühlteichs",
      "Blumenpfl-ºcken" = "Blumenpflücken",
      "Universit-t" = "Universität",
      "St-ºck" = "Stück",
      "St-ºcks" = "Stücks",
      "erz-hlt" = "erzählt",
      "w-chst" = "wächst",
      "d-nischen" = "dänischen",
      "K-nigshof" = "Königshof",
      "hnliches" = "ähnliches",
      "f-llt" = "fällt",
      "Ñhnlichkeit" = "Ähnlichkeit",
      "k-nnten" = "könnten",
      "gez-hlt" = "gezählt"))

df_b <- df_a %>% distinct(word_single)
df_b$duplication <- df_b$word_single
df_b$word_single <- tolower(df_b$word_single)

write_csv(df_b, "word_datasets/words.csv")
```




