---
title: "Replication"
author: "Christopher"
date: "2026-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
library(ggcorrplot)

df_other <- read_excel("data/Conde_other.xlsx")
df_replication <- df_other %>% slice(1:10000)


df_co <- read_csv("data/concr.csv")
df_va <- read_csv("data/val.csv")
df_ar <- read_csv("data/arou.csv")
```

Replication:

```{r pressure, echo=FALSE}
### This reduces the dataframe to only the required columns:
df_co <- df_co %>% select(custom_id, `response/body/choices/0/logprobs/content/0/top_logprobs/0/token`, `response/body/choices/0/logprobs/content/0/top_logprobs/0/logprob`, `response/body/choices/0/logprobs/content/0/top_logprobs/1/token`, `response/body/choices/0/logprobs/content/0/top_logprobs/1/logprob`, `response/body/choices/0/logprobs/content/0/top_logprobs/2/token`, `response/body/choices/0/logprobs/content/0/top_logprobs/2/logprob`, `response/body/choices/0/logprobs/content/0/top_logprobs/3/token`, `response/body/choices/0/logprobs/content/0/top_logprobs/3/logprob`, `response/body/choices/0/logprobs/content/0/top_logprobs/4/token`, `response/body/choices/0/logprobs/content/0/top_logprobs/4/logprob`)

### This renames the columns of the dataframe:
df_co <- df_co %>% rename(word_nr = custom_id, token_1 = "response/body/choices/0/logprobs/content/0/top_logprobs/0/token", logprob_1 = "response/body/choices/0/logprobs/content/0/top_logprobs/0/logprob", token_2 = "response/body/choices/0/logprobs/content/0/top_logprobs/1/token", logprob_2 = "response/body/choices/0/logprobs/content/0/top_logprobs/1/logprob", token_3 = "response/body/choices/0/logprobs/content/0/top_logprobs/2/token", logprob_3 = "response/body/choices/0/logprobs/content/0/top_logprobs/2/logprob", token_4 = "response/body/choices/0/logprobs/content/0/top_logprobs/3/token", logprob_4 = "response/body/choices/0/logprobs/content/0/top_logprobs/3/logprob", token_5 = "response/body/choices/0/logprobs/content/0/top_logprobs/4/token", logprob_5 = "response/body/choices/0/logprobs/content/0/top_logprobs/4/logprob")


### This generates the probabilities for a token based of the logprobability:
df_co$prob_1 <- exp(df_co$logprob_1)
df_co$prob_2 <- exp(df_co$logprob_2)
df_co$prob_3 <- exp(df_co$logprob_3)
df_co$prob_4 <- exp(df_co$logprob_4)
df_co$prob_5 <- exp(df_co$logprob_5)


### This code makes all token-columns to be characters. This is necessary for the next step.
df_co$token_1 <- as.character(df_co$token_1)
df_co$token_2 <- as.character(df_co$token_2)
df_co$token_3 <- as.character(df_co$token_3)
df_co$token_4 <- as.character(df_co$token_4)
df_co$token_5 <- as.character(df_co$token_5)


### This will clean the token_columns, since often they do not contain strictly numbers from 1-7 but also written numbers, or number from different languages. Sometimes even numbers outside of the range of 1-7, or words like "Neutral".
df_co <- df_co %>% mutate(token_3 = recode(token_3, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "NA", "8" = "NA", "۱" = "1", "６" = "6", "siete" = "7", "seven" = "7", "six" = "6"))
df_co <- df_co %>% mutate(token_4 = recode(token_4, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "0", "8" = "0", "۱" = "1", "６" = "6", "six" = "6", "siete" = "7", "seven" = "7", ))
df_co <- df_co %>% mutate(token_5 = recode(token_5, " six" = "6", " siete" = "7", "five" = "5", "01" = "1", " seven" = "7", "seis" = "6", "七" = "7", "१" = "1", "４" = "4", " five" = "5", " seis" = "6", "１" = "1", "５" = "5", "３" = "3", "２" = "2", " cinco" = "5", " sieben" = "7", " " = "NA", "8" = "NA", "۱" = "1", "６" = "6", "six" = "6", "seven" = "7", "siete" = "7", "cinco" = "5", "sieben" = "7"))

df_co <- df_co %>% mutate(
    token_4 = na_if(token_4, "0"))

df_co <- df_co %>% mutate(
    token_5 = na_if(token_5, "0"))

## This code checks which values are found in a given column (best would be only 1-7):
unique(df_co$token_1)
unique(df_co$token_2)
unique(df_co$token_3)
unique(df_co$token_4)
unique(df_co$token_5)

### This code makes all columns numeric:
df_co$token_1 <- as.numeric(df_co$token_1) #=>Token-Columns
df_co$token_2 <- as.numeric(df_co$token_2)
df_co$token_3 <- as.numeric(df_co$token_3)
df_co$token_4 <- as.numeric(df_co$token_4)
df_co$token_5 <- as.numeric(df_co$token_5)
df_co$prob_1 <- as.numeric(df_co$prob_1) #=>Probability-columns
df_co$prob_2 <- as.numeric(df_co$prob_2)
df_co$prob_3 <- as.numeric(df_co$prob_3)
df_co$prob_4 <- as.numeric(df_co$prob_4)
df_co$prob_5 <- as.numeric(df_co$prob_5)

### Now we will generate the weighted_sum based on the tokens and their probabilities:
weighted_sum <- function(df_co) {
  df_co$token_1 * df_co$prob_1 +
  df_co$token_2 * df_co$prob_2 +
  df_co$token_3 * df_co$prob_3 +
  df_co$token_4 * df_co$prob_4 +
  df_co$token_5 * df_co$prob_5}

### This code will add the output as a column:
df_co$weighted_sum <- weighted_sum(df_co)

### This will create a dataframe that contains the words and their weighted_sum for concreteness:

df_co$Word <- df_miss_other$Word 



## This correlates the concreteness ratings from Conde with the ones i generated using their scripts.

cor(df_c)

df_replication$GPT_concr <- as.numeric(df_replication$GPT_concr)

cor(df_replication$GPT_concr, df_co$weighted_sum, method = "pearson", use = "complete.obs") #=> Pearson correlation (0.9940848)
cor(df_replication$GPT_concr, df_co$weighted_sum, method = "spearman", use = "complete.obs") #=> Spearman correlation (0.9960918)

## This code plots the correlation:
df_plot <- data.frame(rep = df_co$weighted_sum, Conde = df_replication$GPT_concr)
  
ggplot(df_plot, aes(x = Conde, y = rep)) +
  geom_point(size =2,alpha = .2, colour = "deeppink2") +
  geom_smooth(method = lm, colour = "black") +
  theme_bw() +
  scale_x_continuous(limits=c(1,7), breaks = 1:7) +
  scale_y_continuous(limits=c(1,7), breaks = 1:7) +
  labs(x = "Conde et al. (2026)")
```




